Error if test.smx is not found

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -24,4 +24,9 @@ jobs:
 
             - name: Check output
               run: |
-                  ls test
+                  if [ -f "./test/test.smx" ]; then
+                      ls test
+                  else
+                      echo "Could not find ./test/test.smx"
+                      exit 1
+                  fi
